DELIMITER //
USE ark //
CREATE OR REPLACE FUNCTION ark_add_request(identifier VARBINARY(16)) RETURNS INT
BEGIN
        -- Check ark.requests for any outstanding (unserviced) requests from this identifier
	-- The identifiers is a UUID generated by the client (iPad) using Apple's identifierForVendor
	-- It will be generated and (re)set upon (re)authentication of a device
	-- This identifier must match a device in ark.devices
        DECLARE total, maximum INT;
	SET total = (SELECT COUNT(*) FROM requests WHERE identifierForVendor=identifier AND serviced=0);
	IF (total <= 0) then
	        INSERT INTO requests (identifierForVendor) VALUES (identifier);
		RETURN (SELECT request_id FROM requests WHERE identifierForVendor=identifier AND serviced=0);
	ELSE
		SET maximum = (SELECT MAX(request_id) FROM (SELECT * FROM requests WHERE identifierForVendor=identifier AND serviced=0) as M);
		RETURN maximum;
	END IF;
END //
DELIMITER ;
